export const columnLabels: Record<string, string> = {
  id: "Identifiant",
  label: "Libellé",
  shortName: "Nom court",
  logo: "Logo",
  description: "Description",
  tags: "Tags",
  purposes: "Finalités",
  targetPopulations: "Populations cibles",
  priorityRestart: "Priorité de redémarrage",
  currentStatusId: "ID Statut actuel",
  applicationId: "ID Application",
  applicationLabel: "Application",

  relationsAsSource: "Relations sortantes",
  "relationsAsSource.targetApplication.label": "Cibles liées (nom)",
  relationsAsTarget: "Relations entrantes",
  "relationsAsTarget.sourceApplication.label": "Sources liées (nom)",
  sourceId: "Source ID",
  targetId: "Target ID",
  type: "Relation Type",

  labels: "Labels",
  "labels.value": "Valeur du label",
  "labels.source": "Source du label",

  hostings: "Hébergements",
  "hostings.provider": "Fournisseur d’hébergement",
  "hostings.label": "Label d’hébergement",
  "hostings.region": "Région",
  "hostings.site": "Site",
  "hostings.nature": "Nature",
  "hostings.platform": "Plateforme",

  compliances: "Conformités",
  "compliances.type": "Type de conformité",

  actors: "Acteurs",
  "actors.firstname": "Prénom de l’acteur",
  "actors.lastname": "Nom de l’acteur",
  "actors.role": "Rôle",
  "actors.type": "Type",
  "actors.email": "Email",
  "actors.organization.sigle": "Organisation",

  externalRessource: "Ressources externes",
  "externalRessource.link": "Lien",
  "externalRessource.description": "Description ressource",
  "externalRessource.type": "Type de ressource",

  // Compliance / DIMA / PDMA / RGAA / DSFR / RGPD / Homologation
  dima_duration_hours: "DIMA Durée (heures)",
  dima_is_hno: "DIMA HNO",
  dima_business_impact: "DIMA Impact métier",
  dima_recovery_plan: "DIMA Plan de reprise",
  dima_recovery_solutions: "DIMA Solutions de reprise",
  dima_last_test_date: "DIMA Date dernier test",
  dima_test_result: "DIMA Résultat test",
  dima_recovery_manager: "DIMA Responsable reprise",
  pdma_duration_hours: "PDMA Durée (heures)",
  pdma_data_types: "PDMA Types de données",
  pdma_backup_frequency: "PDMA Fréquence sauvegarde",
  pdma_backup_method: "PDMA Méthode sauvegarde",
  pdma_backup_storage: "PDMA Stockage sauvegarde",
  pdma_last_test_date: "PDMA Date dernier test",
  pdma_test_result: "PDMA Résultat test",
  pdma_restoration_manager: "PDMA Responsable restauration",
  homologation_date_end: "Homologation Date Fin",
  homologation_rssi_id: "Homologation RSSI ID",
  rgaa_audit_date: "RGAA Date audit",
  rgaa_service_url: "RGAA URL service",
  rgaa_accessibility_url: "RGAA URL accessibilité",
  rgaa_score_percentage: "RGAA Score (%)",
  dsfr_implemented: "DSFR Implémenté",
  dsfr_version: "DSFR Version",
  rgpd_has_aipd: "RGPD AIPD",
  rgpd_dpo_name: "RGPD Nom DPO",

  // Statuses
  status: "Statut",
  statusDate: "Date du statut",

  report: "Signalements",
  "report.description": "Description",
  "report.status": "Statut du signalement",
};
