FROM bitnami/postgresql:latest

# Set environment variables for PostgreSQL
ENV POSTGRESQL_USERNAME=${POSTGRESQL_USER:-puser} \
    POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-ppassword} \
    POSTGRESQL_DATABASE=${POSTGRESQL_DB:-db}


COPY schema.sql /docker-entrypoint-initdb.d/
