services:
  backend:
    image: ${BACKEND_IMAGE_TAG}
    command: pnpm start:prod
    volumes:
      - ./backend/coverage:/app/coverage
      - /app/node_modules
  postgres:
    healthcheck:
      test: [CMD-SHELL, pg_isready, -U, postgres]
      interval: 5s
      timeout: 2s
      retries: 10
