services:
  backend:
    image: ${BACK_IMAGE_TAG}
    pull_policy: always
    build: !reset null
    command: !reset null
    volumes: !reset []

  client:
    image: ${FRONT_IMAGE_TAG}
    pull_policy: always
    ports:
      - 8080:8080
    volumes: !reset
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro

    command: !reset null

  prisma-studio: !reset null
