worker_processes 4;

events { worker_connections 1024; }

# Directive to run nginx as non-root user
pid        /tmp/nginx.pid;

http {
    # https://github.com/dnum-mi/basegun/issues/407
    server_tokens off;

    server {
        listen 8080;
        root  /usr/share/nginx/html;
        include /etc/nginx/mime.types;

        location / {
          try_files $uri $uri/ /index.html;
        }

        error_page  404              /404.html;

        error_page  500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
        # Proxy to backend on /api
        location /api/ {
            proxy_pass         http://backend:3500/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}