import { type Permission } from "@/client";

export interface ColumnConfig {
  field: string;
  header: string;
  sortable?: boolean;
  defaultWidth?: string;
  visible?: boolean;
  requiredPermissions?: Permission[];
  alwaysAvailable?: boolean;
}

export const AVAILABLE_COLUMNS: ColumnConfig[] = [
  {
    field: "quality",
    header: "IQ",
    sortable: true,
    defaultWidth: "80px",
    visible: true,
    alwaysAvailable: true,
  },
  {
    field: "label",
    header: "Nom",
    sortable: true,
    defaultWidth: "300px",
    visible: true,
    alwaysAvailable: true,
  },
  {
    field: "priorityRestart",
    header: "Priorité",
    sortable: true,
    defaultWidth: "160px",
    visible: true,
    alwaysAvailable: true,
  },
  {
    field: "hostingDisplay",
    header: "Hébergement",
    sortable: true,
    defaultWidth: "280px",
    visible: true,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "tag",
    header: "Tags",
    sortable: true,
    defaultWidth: "240px",
    visible: true,
    alwaysAvailable: true,
  },
  {
    field: "moa",
    header: "MOA",
    sortable: false,
    defaultWidth: "200px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "moe",
    header: "MOE",
    sortable: false,
    defaultWidth: "200px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "hostingProviderDisplay",
    header: "Fournisseur",
    sortable: true,
    defaultWidth: "200px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "hostingPlatformDisplay",
    header: "Plateforme",
    sortable: true,
    defaultWidth: "200px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "hostingManagerDisplay",
    header: "Responsable hébergement",
    sortable: false,
    defaultWidth: "200px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "businessDivision",
    header: "Direction métier",
    sortable: true,
    defaultWidth: "120px",
    visible: false,
    alwaysAvailable: true,
  },
  {
    field: "rsimm",
    header: "RSIMM",
    sortable: false,
    defaultWidth: "200px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "dima",
    header: "DIMA",
    sortable: false,
    defaultWidth: "150px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "pdma",
    header: "PDMA",
    sortable: false,
    defaultWidth: "150px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "rgaa",
    header: "RGAA",
    sortable: false,
    defaultWidth: "150px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "dsfr",
    header: "DSFR",
    sortable: false,
    defaultWidth: "150px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "rgpd",
    header: "RGPD",
    sortable: false,
    defaultWidth: "150px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "pra",
    header: "PRA",
    sortable: false,
    defaultWidth: "150px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "homologation",
    header: "Homologation",
    sortable: false,
    defaultWidth: "180px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "homologationDateEnd",
    header: "Date de fin d'homologation",
    sortable: false,
    defaultWidth: "220px",
    visible: false,
    requiredPermissions: ["ColumnRead"],
  },
  {
    field: "status",
    header: "Statut",
    sortable: false,
    defaultWidth: "150px",
    visible: false,
    alwaysAvailable: true,
  },
  {
    field: "applicationViews",
    header: "Nombre de consultations",
    sortable: true,
    defaultWidth: "100px",
    visible: false,
    alwaysAvailable: true,
  },
  {
    field: "technicalMaturity",
    header: "Maturité technique",
    sortable: false,
    defaultWidth: "150px",
    visible: false,
    alwaysAvailable: true,
  },
  {
    field: "businessMaturity",
    header: "Maturité métier",
    sortable: false,
    defaultWidth: "150px",
    visible: false,
    alwaysAvailable: true,
  },
  {
    field: "costMaturity",
    header: "Coûts",
    sortable: false,
    defaultWidth: "120px",
    visible: false,
    alwaysAvailable: true,
  },
];

export const DEFAULT_VISIBLE_COLUMNS = AVAILABLE_COLUMNS.filter((col) => col.visible).map((col) => col.field);
