/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActorActions: typeof import('./components/ActorActions.vue')['default']
    ActorForm: typeof import('./components/form/ActorForm.vue')['default']
    ActorManager: typeof import('./components/ActorManager.vue')['default']
    ActorTab: typeof import('./components/ActorTab.vue')['default']
    AddRelationModal: typeof import('./components/AddRelationModal.vue')['default']
    AllIssues: typeof import('./components/AllIssues.vue')['default']
    AppDate: typeof import('./components/AppDate.vue')['default']
    ApplicationForm: typeof import('./components/form/ApplicationForm.vue')['default']
    ApplicationList: typeof import('./components/ApplicationList.vue')['default']
    ApplicationOverview: typeof import('./components/ApplicationOverview.vue')['default']
    AppLoader: typeof import('./components/AppLoader.vue')['default']
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    ComplianceForm: typeof import('./components/form/ComplianceForm.vue')['default']
    Compliances: typeof import('./components/Compliances.vue')['default']
    CompliancesTab: typeof import('./components/CompliancesTab.vue')['default']
    DeleteConfirmationModal: typeof import('./components/modal/DeleteConfirmationModal.vue')['default']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrCard: typeof import('@gouvminint/vue-dsfr')['DsfrCard']
    DsfrFooter: typeof import('@gouvminint/vue-dsfr')['DsfrFooter']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrSearchBar: typeof import('@gouvminint/vue-dsfr')['DsfrSearchBar']
    EditRelationModal: typeof import('./components/EditRelationModal.vue')['default']
    EventForm: typeof import('./components/form/EventForm.vue')['default']
    Events: typeof import('./components/Events.vue')['default']
    EventsTab: typeof import('./components/EventsTab.vue')['default']
    ExportApplications: typeof import('./components/ExportApplications.vue')['default']
    InformationsGenerales: typeof import('./components/InformationsGenerales.vue')['default']
    LinkForm: typeof import('./components/form/LinkForm.vue')['default']
    Links: typeof import('./components/Links.vue')['default']
    LinksTab: typeof import('./components/LinksTab.vue')['default']
    MyIssues: typeof import('./components/MyIssues.vue')['default']
    NotificationsApplication: typeof import('./components/NotificationsApplication.vue')['default']
    RelationshipsTab: typeof import('./components/RelationshipsTab.vue')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    ReportIssue: typeof import('./components/ReportIssue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchApplications: typeof import('./components/SearchApplications.vue')['default']
  }
}
