/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActorActions: typeof import('./components/ActorActions.vue')['default']
    ActorManager: typeof import('./components/ActorManager.vue')['default']
    AppDate: typeof import('./components/AppDate.vue')['default']
    ApplicationList: typeof import('./components/ApplicationList.vue')['default']
    ApplicationOverview: typeof import('./components/ApplicationOverview.vue')['default']
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    Compliances: typeof import('./components/Compliances.vue')['default']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrBreadcrumb: typeof import('@gouvminint/vue-dsfr')['DsfrBreadcrumb']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrCard: typeof import('@gouvminint/vue-dsfr')['DsfrCard']
    DsfrDataTable: typeof import('@gouvminint/vue-dsfr')['DsfrDataTable']
    DsfrFooter: typeof import('@gouvminint/vue-dsfr')['DsfrFooter']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrModal: typeof import('@gouvminint/vue-dsfr')['DsfrModal']
    DsfrPagination: typeof import('@gouvminint/vue-dsfr')['DsfrPagination']
    DsfrSearchBar: typeof import('@gouvminint/vue-dsfr')['DsfrSearchBar']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    DsfrTabContent: typeof import('@gouvminint/vue-dsfr')['DsfrTabContent']
    DsfrTabItem: typeof import('@gouvminint/vue-dsfr')['DsfrTabItem']
    DsfrTabs: typeof import('@gouvminint/vue-dsfr')['DsfrTabs']
    DsfrTag: typeof import('@gouvminint/vue-dsfr')['DsfrTag']
    ExportApplications: typeof import('./components/ExportApplications.vue')['default']
    InformationsGenerales: typeof import('./components/InformationsGenerales.vue')['default']
    Links: typeof import('./components/Links.vue')['default']
    NotificationsApplication: typeof import('./components/NotificationsApplication.vue')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    ReportIssue: typeof import('./components/ReportIssue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchApplications: typeof import('./components/SearchApplications.vue')['default']
  }
}
