name: Main CI

on:
  push:
    branches:
      - main
        -dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-backend:
    name: Build Backend
    uses: ./.github/workflows/build.yml
    with:
      image: ghcr.io/dnum-mi/referentiel-applications/backend
      context: ./backend
      target: prod

  build-frontend:
    name: Build Frontend
    uses: ./.github/workflows/build.yml
    with:
      image: ghcr.io/dnum-mi/referentiel-applications/frontend
      context: ./frontend
      target: prod

  test-lint:
    name: Test Linting
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run ESLint
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile
          pnpm run lint

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/tests-unit.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

  e2e-tests:
    name: E2E Tests
    uses: ./.github/workflows/tests-e2e.yml
    needs:
      - build-frontend
      - build-backend
    with:
      BACKEND_IMAGE_TAG: ${{ needs.build-backend.outputs.image_tag }}
      FRONTEND_IMAGE_TAG: ${{ needs.build-frontend.outputs.image_tag }}
