name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create new release
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      major-tag: ${{ steps.release.outputs.major }}
      minor-tag: ${{ steps.release.outputs.minor }}
      patch-tag: ${{ steps.release.outputs.patch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pre release new version
        uses: googleapis/release-please-action@v4
        id: release
        with:
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Générer public/version.json
        if: ${{ steps.release.outputs.release_created }}
        run: |
          VERSION=$(node -p "require('./package.json').version")
          mkdir -p public
          echo "{\"version\": \"$VERSION\"}" > public/version.json
