name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create new release
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      major-tag: ${{ steps.release.outputs.major }}
      minor-tag: ${{ steps.release.outputs.minor }}
      patch-tag: ${{ steps.release.outputs.patch }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Pre release new version
        id: release
        uses: googleapis/release-please-action@v4
        with:
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Edit packages versions
        if: ${{ ! steps.release.outputs.release_created }}
        run: |
          echo "${{ steps.release.outputs }}"
          echo "${{ toJson(steps.release.outputs) }}"
          export BRANCH=$(jq -r '.headBranchName' <<<'${{ steps.release.outputs.pr }}')
          git fetch
          git checkout "$BRANCH"
          VERSION=$(jq -r '.version' package.json)
          yq e -i ".version |= \"$VERSION\"" ./frontend/package.json
          yq e -i ".version |= \"$VERSION\"" ./backend/package.json
          git add .
          # Emulate the author of the existing commit (the bot).
          git config user.email "$(git log -n 1 --format='%ae')"
          git config user.name "$(git log -n 1 --format='%an')"
          # Update the PR.
          git commit --amend --no-edit
          git push -f
