name: Test E2E
on:
  workflow_call:
    inputs:
      BACKEND_IMAGE_TAG:
        required: true
        type: string
      FRONTEND_IMAGE_TAG:
        required: true
        type: string

jobs:
  test-e2e-frontend:
    name: Test E2E Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Start stack using docker compose
        run: |
          echo "BACK_IMAGE_TAG=${{ inputs.BACKEND_IMAGE_TAG }}" >> .env
          echo "FRONT_IMAGE_TAG=${{ inputs.FRONTEND_IMAGE_TAG }}" >> .env
          cat .env
          . .env
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up client backend postgres keycloak -d

      - name: Wait for Keycloak to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8082/realms/referentiel-applications/.well-known/openid-configuration; then
              echo "Keycloak is ready"
              exit 0
            fi
            echo "Waiting for Keycloak..."
            sleep 5
          done
          echo "Keycloak did not become ready in time"
          exit 1

      - name: Wait for Frontend to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080 | grep -q "<title>Référentiel des applications</title>"; then
              echo "Frontend is ready"
              exit 0
            fi
            echo "Waiting for Frontend..."
            sleep 5
          done
